<script setup>
	import { Notyf } from 'notyf';
	import { ref, onMounted, onBeforeUnmount } from 'vue';

	const notyf = new Notyf();

	const name = ref("");
	const email = ref("");
	const message = ref("");
	const isLoading = ref(false);

	// 1. Web3Forms Access Key
	const WEB3FORMS_ACCESS_KEY = "91c0b0e7-58c2-48d8-a99c-f04255e380e5"; 

	// Email subject that will appear when a form submission is received.
	const subject = "New message from Gladys Ramos Portfolio";

	// The verification token generated by hCaptcha
	const hcaptchaToken = ref('');

	// The submitForm() function handles the contact form submission.
	const submitForm = async () => {

		// Ensure the user completes the hCaptcha challenge before submitting the form.
		if (!hcaptchaToken.value) {
			notyf.error('Please verify that you are not a robot');
			return;
		}

		// While the email is being sent, disable the button and change text to "Sending..."
		isLoading.value = true;

		try {
			// Send HTTP request to Web3Forms API
			const response = await fetch("https://api.web3forms.com/submit", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
					"Accept": "application/json"
				},
				body: JSON.stringify({
					access_key: WEB3FORMS_ACCESS_KEY,
					subject: subject,
					name: name.value,
					email: email.value,
					message: message.value,
					// Send the verification token using the explicit hCaptcha key parameter
					"h-captcha-response": hcaptchaToken.value
				})
			});

			const result = await response.json();

			if (result.success) {
				console.log(result);
				isLoading.value = false;
				notyf.success("Message Sent!");
				
				// Clear form inputs on success
				name.value = "";
				email.value = "";
				message.value = "";
			} else {
				isLoading.value = false;
				notyf.error(result.message || "Failed to send message.");
			}
		} catch (error) {
			console.log(error);
			isLoading.value = false;
			notyf.error("Failed to send message.");
		} finally {
			resetHcaptcha();
		}
	}

	/* hCaptcha Integration Settings */

	// 2. Put your hCaptcha SITE KEY here (from your hCaptcha dashboard)
	const HCAPTCHA_SITE_KEY = 'YOUR_HCAPTCHA_SITE_KEY_HERE';   

	const hcaptchaContainer = ref(null);
	const hcaptchaWidgetId = ref(null);

	// Captures the token when a user passes the test successfully
	function onHcaptchaSuccess(token) {
		hcaptchaToken.value = token;
	}

	// Clears the token if the user's validation session times out
	function onHcaptchaExpired() {
		hcaptchaToken.value = '';
	}

	function renderHcaptcha() {
		if (!window.hcaptcha) {
			console.error('hCaptcha script has not loaded into the window object yet');
			return;
		}

		// Explicitly renders the hCaptcha widget into our container element
		hcaptchaWidgetId.value = window.hcaptcha.render(hcaptchaContainer.value, {
			sitekey: HCAPTCHA_SITE_KEY,
			theme: 'light',
			callback: onHcaptchaSuccess,
			'expired-callback': onHcaptchaExpired,
		});
	}

	function resetHcaptcha() {
		if (hcaptchaWidgetId.value !== null && window.hcaptcha) {
			window.hcaptcha.reset(hcaptchaWidgetId.value);
			hcaptchaToken.value = '';
		}
	}

	// Polls the window runtime to mount the widget as soon as the external script arrives
	onMounted(() => {
		const interval = setInterval(() => {
			if (window.hcaptcha && window.hcaptcha.render) {
				renderHcaptcha();
				clearInterval(interval);
			}
		}, 100);

		onBeforeUnmount(() => {
			clearInterval(interval);
		});
	});  
	
</script>

<template>
	<h1 class="text-center my-4 pt-5" id="contact">Contact</h1>
	<div class="contact-section container">
		<div class="row align-items-center mt-4">
			<div class="col-md-6 mb-4 mb-md-0 text-center">
				<div class="p-5 bg-light rounded shadow-sm">
					<h4>Let's Build Something Together!</h4>
					<p class="text-muted">Drop me a line or connect with me via my professional networks below.</p>
				</div>
			</div>
			<div class="col-md-6">
				<form @submit.prevent="submitForm">
					<div class="mb-3">
						<input type="text" v-model="name" class="form-control" placeholder="Full Name" required>
					</div>
					<div class="mb-3">
						<input type="email" v-model="email" class="form-control" placeholder="Email Address" required>
					</div>
					<div class="mb-3">
						<textarea class="form-control" v-model="message" rows="6" placeholder="Your Message" required></textarea>
					</div>
					
					<div class="mb-3 d-flex justify-content-center justify-content-md-start">
						<div ref="hcaptchaContainer"></div>
					</div>

					<div class="d-flex justify-content-between align-items-center flex-wrap gap-3">
						<button type="submit" class="btn btn-primary" :disabled="isLoading">
							{{ isLoading ? 'Sending...' : 'Send Message' }}
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</template>